# main config file for ARIMA baseline
output_dir: ${oc.env:HOME}/StructuredKalmanSmoother/results
data_dir: ${oc.env:HOME}/StructuredKalmanSmoother/datasets
dataset: advection_30x30_obs=0.9_T=20_diff=0.01_adv=constant_ntrans=4_1block=True_kmax=3_0
experiment: test_ARIMA

# final model evaluation?
final: true
save_prediction: false

seed: 0
n_iterations: 10000
inference_rtol: 1e-7
arima_params: [1, 0, 1]
#seasonal_params: [1, 0, 1, 24]

