# main config file
output_dir: ${oc.env:HOME}/StructuredKalmanSmoother/results
#dataset: pems_start=0_end=215
data_dir: ${oc.env:HOME}/StructuredKalmanSmoother/datasets
dataset: AQ_PM25_T=400_2015_3_log=True_mask=spatial_block_0.62
#dataset: spatiotemporal_10x10_obs=0.9_T=20_diff=0.01_adv=constant_ntrans=4_1block=True_0
experiment: testing

# final model evaluation?
final: false

# dgmrf settings
noise_std: 0.1
learn_noise_std: false
n_layers: 1
non_linear: false
fix_gamma: false
gamma_value: 1
log_det_method: eigvals
use_bias: true
n_training_samples: 10
n_post_samples: 100
vi_layers: 1
use_features: false
coeff_inv_std: 0.0001
independent_time: false
weighted_dgmrf: false
weighted_vi: false

## DGMRF settings
#use_dynamics: false
#transition_type: none
#n_transitions: 0

# ST-DGMRF settings
use_dynamics: true
n_transitions: 1
use_dynamics_bias: true
use_vi_dynamics: false
use_hierarchy: false
transition_type: diffusion
n_layers_temporal: 1
vi_transition_type: diffusion

use_KS: false

seed: 0
optimizer: adam
lr: 0.01
val_interval: 100
n_iterations: 10000
inference_rtol: 1e-7
max_cg_iter: 500
device: gpu
early_stopping_patience: 100

# ARIMA settings
arima_params: [1, 0, 1]
#seasonal_params: [1, 0, 1, 24]

# MLP settings
MLP_hidden_dim: 10
MLP_nonlinearity: ReLU

