# main config file for MLP baseline
output_dir: ${oc.env:HOME}/StructuredKalmanSmoother/results
data_dir: ${oc.env:HOME}/StructuredKalmanSmoother/datasets
dataset: advection_30x30_obs=0.9_T=20_diff=0.01_adv=constant_ntrans=4_1block=True_0
experiment: test_MLP

# final model evaluation?
final: true
save_prediction: false

seed: 0
optimizer: adam
lr: 0.01
val_interval: 100
n_iterations: 10000
device: gpu
early_stopping_patience: 100
MLP_hidden_dim: 16
MLP_nonlinearity: ReLU

