# main config file for EnKS baseline
output_dir: ${oc.env:HOME}/StructuredKalmanSmoother/results
data_dir: ${oc.env:HOME}/StructuredKalmanSmoother/datasets
dataset: advection_30x30_obs=0.9_T=20_diff=0.01_adv=constant_ntrans=4_1block=True_kmax=3_0
experiment: test_EnKS
device: gpu

# final model evaluation?
final: true
save_prediction: false

noise_std: 0.01
seed: 0
inference_rtol: 1e-7

ensemble_size: 10000
initial_std_states: 10
initial_std_params: [0.01, 0.1, 0.1]
transition_std_states: 0.1
transition_std_params: 0.01

estimate_params: false
