#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --job-name=sweep_job
#SBATCH --time=12:00:00
#SBATCH --output=slurm_output_%A_%a.out
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=f.lippert@uva.nl

# run this file as "sbatch sweep.job sweep_id

source activate stdgmrf

cd $HOME/StructuredKalmanSmoother/scripts

which python

nvidia-smi

export WANDB_DIR=$HOME/StructuredKalmanSmoother

wandb agent $1

